dist: xenial

language: python

matrix:
  include:
  - name: "Python 3.6 Unit Test"
    python: 3.6
    env: PYTHON_VERSION=3.6 NAME="UNIT"
  - name: "Python 3.6 Lint"
    python: 3.6
    env: PYTHON_VERSION=3.6 NAME="LINT"

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker pull conda/miniconda3
  - docker --version

install:
  # Build docker image
  - . ./scripts/container.sh --build

  # Print conda details
  - docker run --rm pymc4:latest bash -c "conda info -a"

  # Print conda environment details
  - docker run --rm pymc4:latest bash -c "conda list && pip freeze"

  # Install packages needed for service integration
  - if [[ $NAME == UNIT ]]; then pip install coveralls ; fi
  - if [[ $NAME == LINT ]]; then pip install coveralls ; fi

script:

  # Tests command is default in dockerfile cmd
  - if [[ $NAME == UNIT ]]; then docker run  --mount type=bind,source="$(pwd)",target=/opt/pymc4 --name pymc4_test pymc4:latest bash -c \
                                              "pytest -v pymc4/tests/ --cov=pymc4/";
    fi

  - if [[ $NAME == LINT ]]; then docker run pymc4:latest bash -c "./scripts/lint.sh";
    fi

after_success:
  - echo $(pwd)
  - ls -la
  - if [[ $NAME == UNIT ]]; then sed -i 's/\/opt\/pymc4/\/home\/travis\/build\/pymc4-devs\/pymc4/g' .coverage; fi
  - if [[ $NAME == UNIT ]]; then coveralls; fi

  - if [[ $NAME == LINT ]]; then sed -i 's/\/opt\/pymc4/\/home\/travis\/build\/pymc4-devs\/pymc4/g' .coverage; fi
  - if [[ $NAME == LINT ]]; then coveralls; fi
